# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  vm_hostname: union01.myorg.chefdemo.net
  #gui: true
  # Mount local /Users/apop/chef-kits folder as /mnt/share on the VM
  synced_folders:
  - ['~/chef-kits', '/mnt/share', 'disabled: false']
  customize:
    cpus: 2
    memory: 2048
    name: union01.myorg.chefdemo.net

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  # Install this exact version of chef-client
  #require_chef_omnibus: 12.4.1
  # Use the local chef-client rpm specified in install_chef_rpm.sh:
  #chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :disabled

platforms:
  - name: centos-72
    driver:
      box: 'chef/centos-7.2'
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box
      #box_url: file:///Users/srussell/Source//Pushjobs/opscode_centos-6.6_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ['private_network', {ip: '192.168.56.50'}]

suites:
  - name: default
    data_bag_path: "test/integration/data_bags"
    run_list:
      - recipe[push-jobs::default]
    attributes:
      push_jobs:
        secrets_type: "databag"
        secrets_source: "delivery_secrets"
        use_package_manager: false
        chef_username: "srv-delivery"
        url_chef: 'https://chef.myorg.chefdemo.net'
        url:
          chef: 'chef.myorg.chefdemo.net'
          delivery: 'delivery.myorg.chefdemo.net'
          supermarket: 'supermarket.myorg.chefdemo.net'
# the https is needed for the chef server url, to be used
# in the push-jobs-client.rb
